name: Hello World

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world"
